---
name: Trunk Code Quality

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Trunk Code Quality
    permissions:
      actions: read
      checks: write
      contents: read
    uses: z-shell/.github/.github/workflows/trunk.yml@9c22447f8270816e097260f6504de0a85d31b057
    with:
      arguments: --no-progress
