---
name: "✅ Zsh"
on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
    paths:
      - "*.zsh"
      - "functions/.*"
  pull_request:
    branches: [main]
    paths:
      - "*.zsh"
      - "functions/.*"
  workflow_dispatch: {}

jobs:
  zsh-matrix:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.set-matrix.outputs.files }}
    steps:
      - name: "⤵️ Check out code from GitHub"
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - name: "Set matrix output"
        id: set-matrix
        run: |
          MATRIX="$(find . -type d -name 'doc' -prune -o -type f \( -iname '*.zsh' -o -iname '.completion-*' \) -print | jq -ncR '{"include": [{"file": inputs}]}')"
          echo "files=${MATRIX}" >> $GITHUB_OUTPUT

  zsh-n:
    runs-on: ubuntu-latest
    needs: zsh-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.zsh-matrix.outputs.output1) }}
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3
      - name: "⚡ Install dependencies"
        run: sudo apt update && sudo apt-get install -yq zsh
      - name: "⚡ zsh -n: ${{ matrix.file }}"
        env:
          ZSH_FILE: ${{ matrix.file }}
        run: |
          zsh -n "${ZSH_FILE}"
      - name: "⚡ zcompile ${{ matrix.file }}"
        env:
          ZSH_FILE: ${{ matrix.file }}
        run: |
          zsh -fc "zcompile ${ZSH_FILE}"; rc=$?
          ls -al "${ZSH_FILE}.zwc"; exit "$rc"
